library(e1071)
setwd("/home/yashwanth/Downloads")
dataset = read.csv('glasses.csv')
library(caTools)
library(ggplot2)
str(dataset)
set.seed(0)
split <- sample.split(dataset$Type, SplitRatio = 3/4)

training_set=subset(dataset,split==TRUE)
test_set=subset(dataset,split==FALSE)
plot(dataset)
model <- svm(Type~.,data=training_set, kernel= "sigmoid")
summary(model)
names(model)
plot(model,test_set, Si~Ca, slice = list( Na = 10,Mg = 3))
pred <- predict(model,test_set)
tab <- table(pred , test_set$Type)
print(tab)
Accuracy <- sum(diag(tab))/sum(tab)*100
cat("Accuracy :",Accuracy)
