bnk=read.csv('bank.csv')
str(bnk)
bnk$balance <-(bnk$balance-min(bnk$balance)) /(max(bnk$balance)-min(bnk$balance))
bnk$age <- (bnk$age-min(bnk$age)) / (max(bnk$age)-min(bnk$age))
bnk$previous <- (bnk$previous-min(bnk$previous)) /(max(bnk$previous)-min(bnk$previous))
bnk$campaign <- (bnk$campaign-min(bnk$campaign)) /(max(bnk$campaign)-min(bnk$campaign))
table(bnk$education)
levels(bnk$education)
head(model.matrix(~education, data=bnk))
bnk$education <- relevel(bnk$education, ref = "secondary")
head(model.matrix(~education, data=bnk))
bnk_matrix <- model.matrix(~age+job+marital+education+default+balance+housing+loan+poutcome+campaign+previous+y, data=bnk)
colnames(bnk_matrix)
colnames(bnk_matrix)[3] <- "jobbluecollar"
colnames(bnk_matrix)[8] <- "jobselfemployed"
col_list <- paste(c(colnames(bnk_matrix[,-c(1,28)])),collapse="+")
col_list <- paste(c("yyes~",col_list),collapse="")
f <- formula(col_list)
library(neuralnet)
set.seed(7896129)
nmodel <- neuralnet(f,data=bnk_matrix,hidden=1,threshold = 0.01,learningrate.limit = NULL,learningrate.factor =list(minus = 0.5, plus = 1.2),algorithm = "rprop+")
output <- compute(nmodel, bnk_matrix[,-c(1,28)],rep=1)
summary(output)
plot(nmodel)

